name: Quality Validation

on:
  workflow_call:

jobs:

  quality:

    runs-on: ubuntu-latest

    strategy:

      matrix:
        quality-check:
          - semgrep
          - audit

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # 🔐 Semgrep
      - name: Semgrep Scan
        if: matrix.quality-check == 'semgrep'
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          
      - name: npm audit
        if: matrix.quality-check == 'audit'
        run: npm audit --audit-level=high