name: Quality Validation

on:
  workflow_call:

jobs:

  quality:

    runs-on: ubuntu-latest

    strategy:

      matrix:
        quality-check:
          - semgrep
          - audit

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Semgrep SAST
        if: matrix.quality-check == 'semgrep'
        run: |
            docker run --rm -v "$(pwd):/src" semgrep scan /src

      - name: npm audit
        if: matrix.quality-check == 'audit'
        run: npm audit --audit-level=high